export const sliderImgs = [
    './assets/img/flag.jpg',
    './assets/img/qc.jpg',
    './assets/img/qc2.jpg',
    './assets/img/slide4.webp',
];
export const legends = [
    {
        name: 'sir alex ferguson',
        img: './assets/img/legend_img_ferguson.jpg',
        pngImg: './assets/img/ferguson_img.png',
        nation: 'Scotland',
        birth: '31/12/1941',
        nationImg: './assets/img/scotland.png',
        description:
            'Sir Alexander Chapman Ferguson CBE former football manager and player, widely known for managing Manchester United from 1986 to 2013. He is considered by many to be one of the greatest managers of all time and he has won more trophies than any other manager in the history of football. As a player, he is best known for his stint with Rangers.',
        appearance: '1000',
        goals: '1000',
        primierCup: 4,
        faCup: 2,
        faCharity: 4,
        championCup: 2,
        view: 'general',
        animated: true,
    },
    {
        name: 'eric catona',
        img: './assets/img/legend_img_catona.jpg',
        pngImg: './assets/img/catona_img.png',
        nation: 'France',
        birth: '24/5/1966',
        nationImg: './assets/img/france.png',
        description:
            '"Le Roi”.“Le Dieu”. Or good old – but never, ever, plain old – Eric. Whatever you want to call Monsieur Cantona, the Frenchman’s four-and-a-half seasons at Old Trafford are the stuff of legend.',
        appearance: '182',
        goals: '82',
        view: 'general',
        animated: true,
    },
    {
        name: 'ryan giggs',
        img: './assets/img/legend_img_giggs.jpg',
        pngImg: '',
        nation: 'England',
        birth: '24/10/1985',
        nationImg: './assets/img/england.png',
        description:
            'You must have a rare and special football talent to impress the great Sir Bobby Charlton. The United legend summed up Paul Scholes perfectly: "He’s always so in control and pinpoint accurate with his passing – a beautiful player to watch."',
        appearance: '718',
        goals: '155',
        primierCup: 4,
        faCup: 2,
        faCharity: 4,
        championCup: 2,
        view: 'general',
        animated: true,
    },
    {
        name: 'bobby charlton',
        img: './assets/img/legend_img_charlton.jpg',
        pngImg: '',
        nation: 'England',
        birth: '11/10/1937',
        nationImg: './assets/img/england.png',
        description:
            'Nobody embodies the values of Manchester United better than Sir Bobby Charlton. Having survived the trauma of the Munich Air Disaster when aged just 20, he played as if every game was for his fallen colleagues, recovering from his injuries to reach the pinnacle for both club and country. In a 17-year playing career with the Reds, he played 758 games and scored 249 goals - both of which were longstanding records until, respectively, Ryan Giggs in 2008 and Wayne Rooney in 2017 surpassed his feats.',
        appearance: '758',
        goals: '249',
        primierCup: 4,
        faCup: 2,
        faCharity: 4,
        championCup: 2,
        view: 'general',
        animated: true,
    },
    {
        name: 'paul scholes',
        img: './assets/img/legend_img_scholes.jpg',
        pngImg: '',
        nation: 'England',
        birth: '24/10/1985',
        nationImg: './assets/img/england.png',
        description:
            'You must have a rare and special football talent to impress the great Sir Bobby Charlton. The United legend summed up Paul Scholes perfectly: "He’s always so in control and pinpoint accurate with his passing – a beautiful player to watch."',
        appearance: '718',
        goals: '155',
        primierCup: 4,
        faCup: 2,
        faCharity: 4,
        championCup: 2,
        view: 'general',
        animated: true,
    },
    {
        name: 'wayne rooney',
        img: './assets/img/legend_img_rooney.jpg',
        pngImg: './assets/img/rooney_img.png',
        nation: 'England',
        birth: '16/11/1974',
        nationImg: './assets/img/england.png',
        description:
            "Wayne Rooney is Manchester United's all-time leading scorer and the only player to have scored 250 goals for the Reds.",
        appearance: '559',
        goals: '253',
        primierCup: 4,
        faCup: 2,
        faCharity: 4,
        championCup: 2,
        view: 'general',
        animated: true,
    },
    {
        name: 'ole gunnar solskjaer',
        img: './assets/img/legend_img_ole.jpg',
        pngImg: './assets/img/ole_img.png',
        nation: 'Norway',
        birth: '26/02/1973',
        nationImg: './assets/img/norway.png',
        description:
            'Ole Gunnar Solskjaer reluctantly called time on his United playing career on 28 August 2007 – 11 years and three days after it began with a goalscoring debut.',
        appearance: '366',
        goals: '126',
        primierCup: 4,
        faCup: 2,
        faCharity: 4,
        championCup: 2,
        view: 'general',
        animated: true,
    },
    {
        name: 'cristiano ronaldo',
        img: './assets/img/legend_img_ronaldo.jpg',
        pngImg: './assets/img/ronaldo_img.png',
        nation: 'Portugal',
        birth: '05/02/1985',
        nationImg: './assets/img/portugal.png',
        description:
            'Cristiano Ronaldo exhausted all superlatives during his six years with United, while he matured from an inexperienced, young winger in 2003 into officially the best footballer on the planet in 2009.',
        appearance: '292',
        goals: '118',
        primierCup: 4,
        faCup: 2,
        faCharity: 4,
        championCup: 2,
        view: 'general',
        animated: true,
    },
    {
        name: 'ruud van nistelrooy',
        img: './assets/img/legend_img_ruud.jpg',
        pngImg: '',
        nation: 'Netherland',
        birth: '01/07/1976',
        nationImg: './assets/img/netherland.png',
        description:
            'Arguably one of world football’s biggest names, David Beckham is a global phenomenon but a part of him will be forever Red.',
        appearance: '394',
        goals: '85',
        primierCup: 4,
        faCup: 2,
        faCharity: 4,
        championCup: 2,
        view: 'general',
        animated: true,
    },
    {
        name: 'david beckham',
        img: './assets/img/legend_img_beckham.jpg',
        pngImg: './assets/img/beckham_img.png',
        nation: 'England',
        birth: '02/05/1975',
        nationImg: './assets/img/england.png',
        description:
            'Sir Alexander Chapman Ferguson CBE former football manager and player, widely known for managing Manchester United from 1986 to 2013. He is considered by many to be one of the greatest managers of all time and he has won more trophies than any other manager in the history of football. As a player, he is best known for his stint with Rangers.',
        appearance: '1200',
        goals: '1000',
        primierCup: 4,
        faCup: 2,
        faCharity: 4,
        championCup: 2,
        view: 'general',
        animated: true,
    },
];
